### PR TITLE
Fixes for v0.7, remove Distributions as a dependence.

### PR DESCRIPTION
**Pull request by tpapp**
Re-implemented a normal type for testing, using quantile functions directly from StatsFuns.

Specified versions for dependencies.

Made RNG explicit everywhere.

### CODE REVIEW

**Comment by mcreel** [comment]
I have been gearing up to try out this interesting package for some approximate Bayesian computing applications. I see you have switched to StatsFuns, instead of Distributions. I may need to do that for a package of mine. Can you make any comments: is it a smooth transition? It appears to be straightforward.

**Comment by tpapp** [comment]
ABC should work as long as your posterior is differentiable. 

I removed Distributions from the tests out of necessity, since it does not work for v0.7 yet, and I preferred my own parametrization of the multivariate normal (the only distribution I am using for tests as of now). It was relatively smooth, but then again, I am not using a lot of distributions and related functions. If you do, it may not be worth it, just wait and things should get fixed soon.

StatsFuns is only needed for a chi-square test quantile.

**Comment by mcreel** [comment]
For my package, I just need quantiles of distributions related to the normal, so StatsFuns will work, I think.

Regarding HMC, my criterion is the Chernozhukhov-Hong Laplace version of GMM. I am using a function that lags a variable, which caused some problem with automatic differentiation. I'm pretty sure it will be easy to fix though. Just need some time. Your package looks very nice.

**Comment by tpapp** [comment]
Great, if you need any extensions to the API, just let me know. A reorganization is coming anyway, because I want to use homotopy continuations to implicitly solved models.

**Comment by tpapp** [comment]
This is rather a mess now. Closing in favor of #16 and subsequent PRs, some changes will be backported.

**Pull request closed without merging**
