### PR TITLE
experimental iterator interface

### PR DESCRIPTION
**Pull request by tpapp**

### CODE REVIEW

**Comment by tpapp** [comment]
@cscherrer, please kindly review this and tell me if I can improve anything.

**Comment by cscherrer** [comment]
Nice! I really like that `ℓq` and `∇ℓq` are available as well, think we can do some interesting things with that.

It would be great to have an `iterate` method as well. I think it would be something like 

```julia
function iterate(steps::DynamicHMC.MCMCSteps, state=Q) 
    Q, tree_stats = mcmc_next_step(steps, Q)
    ((Q, tree_stats), Q)
end
```

But the initial `Q` will need to come from somewhere. Maybe a closure will get us there?

**Comment by cscherrer** [comment]
Got it working, using ResumableFunctions.jl:
https://github.com/cscherrer/Soss.jl/blob/dev/src/dynamicHMC.jl

**Comment by tpapp** [comment]
Great to see that this is working for you.

I am reluctant to make an interface for `iterate`, since I don't really think of simulation as iteration (though I recognize the analogues).

Is there anything else you need here? Otherwise I would just merge this and tag a release.

**Comment by cscherrer** [comment]
Sounds good, thank you!

**Pull request merged**
