### PR TITLE
minor modifications related to factoring out LogDensityProblemsAD

### PR DESCRIPTION
**Pull request by tpapp**

### CODE REVIEW

**Comment by devmotion** [comment]
Why does this change require Julia 1.8? AFAICT we can test Turing not on < 1.8 anymore with this change, unless we remove tests with DynamicHMC.

**Comment by tpapp** [comment]
I used 1.8 features in recent PRs, notably #170. While of course one can always work around anything, this made life much simpler, and some allocations got eliminated under the hood. In particular, JuliaLang/julia#43127 fixed a lot of bugs for me so I no longer need workarounds and can organize code more sanely.

**Comment by devmotion** [comment]
> I used 1.8 features in recent PRs, notably https://github.com/tpapp/DynamicHMC.jl/pull/170.

It's not obvious to me what changes in that PR require Julia 1.8. Can you explain what exactly broke Julia 1.6 and 1.7?

Generally, I agree that it is sometimes painful and not worth it trying to support (too) old Julia versions. So I assume by now most actively maintained packages that needed workarounds on Julia < 1.6 have bumped the compat bound to 1.6 (I am not completely on board with the SciML policy though that **demands** that support for Julia < 1.6 is dropped since I don't see the need if the package just works and is tested on older Julia version). Personally I think the LTS version is a good common ground since it makes the package system more accessible for people that work in a more restricted environment and can't update the Julia version as easily (or work on longer projects and don't update too often to avoid hunting down problems introduced by newer versions).

**Comment by tpapp** [comment]
Generally I would like to be considerate if people really, really need 1.6, but compiling a detailed list is exactly the kind of effort I am trying to avoid --- it would be tantamount to backporting stuff and peppering the code with `@static if VERSION <= ...` etc. 

I am open to bringing back 1.6 support, but I would recommend that you just start tests on 1.6 and see what breaks. If I remember correctly, some test dependencies also need 1.8, but again compiling a detailed list is not something I have resources for at the moment.

I am happy to accept PRs unless they make the code really ugly again. Also, please open an issue for bringing back 1.6 support.

Regarding the argument about restricted environments: note that whatever versions are out there will keep working on 1.6 forever. People can just use them.

**Comment by devmotion** [comment]
Tests passed locally with the updated LogDensityTestSuite, so I'm not sure what the problem was. Actually even the tests which are supposed to fail on Julia 1.6 passed locally: https://github.com/tpapp/DynamicHMC.jl/pull/174

**Comment by devmotion** [comment]
The CI logs in this PR suggest that possibly the only issue was LogDensityTestSuite: https://github.com/tpapp/DynamicHMC.jl/actions/runs/3647513077/jobs/6160379208

**Comment by tpapp** [comment]
@devmotion, just want to say thank you for investigating and fixing this.

**Pull request merged**
